import os
from dotenv import load_dotenv
load_dotenv() # Force reload to pick up the new ALERT_EMAIL

import cv2
import numpy as np
from datetime import datetime
from config import SNAPSHOT_DIR

# Need to reload config since we modified .env
import config
config.ALERT_RECIPIENT = os.getenv("ALERT_EMAIL")

from alerter import send_alert

def run_test():
    print("Creating dummy snapshot...")
    img = np.zeros((200, 200, 3), dtype=np.uint8)
    cv2.putText(img, "TEST FIRE", (20, 100), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255), 2)
    path = os.path.join(SNAPSHOT_DIR, "test_email.jpg")
    cv2.imwrite(path, img)

    result = {
        "severity": "high",
        "hazard_type": "fire",
        "confidence": 0.99,
        "description": "This is a test email generated by your AI Agent."
    }

    print(f"Sending email from {config.SMTP_USER} to {config.ALERT_RECIPIENT}...")
    success = send_alert(result, path, datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
    if success:
        print("Test completed successfully! Email was sent.")
    else:
        print("Test failed. Email was NOT sent.")

if __name__ == "__main__":
    run_test()
